### ISSUE TITLE
Bugged

### ISSUE THREAD

**Issue by Tanae** [mynian/LegionHonor#4]
Date: 2018-02-18 17:48:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\LegionHonor\LegionHonor.lua line 53:
'(' expected near '='
Debug:

Locals:

AddOns:
Swatter, v7.5.5724 (TasmanianThylacine)
ACP, vr250 
AethysCache, v7.3.2.03
AethysCore, v7.3.2.03
AethysRotation, v7.3.2.03
AlreadyKnown, v1.17
AltTabber, vv1.9.6
AngryKeystones, v
AnnounceInterrupts, v1.6h
AnnoyingChatFade, v1.0
APTokenPercent, v1.5.3
ArtifactButton, v5.0
ArtifactPathFinder, v1.6.0
ArtifactTab, v2.3.2
AucAdvanced, v7.5.5724 (TasmanianThylacine)
AucFilterBasic, v7.5.5724 (TasmanianThylacine)
AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
AucStatHistogram, v7.5.5724 (TasmanianThylacine)
AucStatiLevel, v7.5.5724 (TasmanianThylacine)
AucStatPurchased, v7.5.5724 (TasmanianThylacine)
AucStatSales, v7.5.5724.5598(7.5/embedded)
AucStatSimple, v7.5.5724 (TasmanianThylacine)
AucStatStdDev, v7.5.5724 (TasmanianThylacine)
AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
AutoAcceptEnchantReplace, v
AutoJunkSeller, v1.0.5
AutoLootPlus, v1.2.2
AutoRepair, v
AutoTurnIn, v7.0.9
Aye, v1.0.6
Babylonian, v5.1.DEV.332(/embedded)
BadBoy, vv7.3.92
BadPet, vv1.0.11
Bartender4, v4.7.10
BattlegroundSpiritReleaser, v
BGCallouts, v7.0
CalendarChecker, v1.2.2
CanIMogIt, v7.3.2v1.6
CantSim, v0.3-beta
ClassSpecStats, v1.22
CombatLogRemover, v1.4.2
Configator, v5.1.DEV.431(/embedded)
ConjuredAnnouncer, v2.3
CooldownCount, v7.0.2
CourtOfStarsGossipHelper, v1.05
CrapAway, v
DailyGlobalCheck, v
DailyGlobalCheckGarrisonMissions, v
DailyGlobalCheckInstanceLockouts, v
DailyGlobalCheckLegionRareMobs, v
DailyGlobalCheckLegionTreasureChests, v
DailyGlobalCheckLegionWorldQuests, v
DailyGlobalCheckWodRareMobs, v
DailyGlobalCheckWodTreasureChests, v
DailyGlobalCheckWorldBosses, v
DBMArchaeology, v
DBMCore, v7.3.22
DBMDefaultSkin, v
DBMInterrupts, v6.2.0
DBMLDB, v
DBMSpellTimers, v
DBMStatusBarTimers, v
DebugLib, v5.1.DEV.337(/embedded)
DungeonLocations, v7.3.0-1.3.2
EasyObliterate, v30
EasyDeleteConfirm, v
GTFO, v4.44.3
HandyNotes, vv1.4.15
HandyNotesAchievements, v0.4.19
HandyNotesArgus, v0.20.0
HandyNotesLegionClassOrderHalls, vv1.25
HandyNotesLegionMagePortals, v1.1
HandyNotesLegionTreasures, v1
HandyNotesLongForgottenHippogryph, v1
HandyNotesLorewalkers, v1
HandyNotesSuramarShalAranTelemancy, vv1.15
HandyNotesTimelessIsleChests, v1.18
HandyNotesTravelGuide, vv1.7
HHTD, v2.4.6
InstancePortals, v8
KCrazyArrowHide, v17
KeystoneHelper, v7.3.0.1
LegionHonor, v1.3.0
LibExtraTip, v5.12.DEV.430(/embedded)
Stubby, v7.5.5724 (TasmanianThylacine)
TipHelper, v5.12.DEV.405(/embedded)
TomTom, vv70300-1.0.0
BlizRuntimeLib_enUS v7.3.5.70300 <none>
(ck=d92)

**Comment by mynian** [comment]
fixed in latest release
